services:
  app:
    build: .
    container_name: alumusic_app
    volumes:
      - .:/app
    environment:
      - FLASK_APP=main.py
    env_file:
      - .env
    depends_on:
      - db

  nginx:
    build: ./nginx
    container_name: alumusic_nginx
    ports:
      - "80:80"
    depends_on:
      - app

  db:
    image: postgres:15-alpine
    container_name: alumusic_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

  redis:
    image: redis:7-alpine
    container_name: alumusic_redis

  worker:
    build: .
    container_name: alumusic_worker
    command: celery -A main:celery worker --loglevel=info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - redis
      - db
      - app
  
volumes:
  postgres_data: